In [1]:
import pandas as pd

In [6]:
data = {
    'Producto':['Manzanas', 'Naranjas', 'Platanos', 'Uvas', 'Peras'],
    'Precio': [100, 80, 60, 120, 90],
    'Stock': [30, 50, 20,60, 40]
}

df = pd.DataFrame(data)
df.set_index('Producto', inplace = True)
df

          Precio  Stock
Producto
Manzanas     100     30
Naranjas      80     50
Platanos      60     20
Uvas         120     60
Peras         90     40

In [4]:
df.drop(index = 'Platanos', axis=0, inplace=True)

In [5]:
df

          Precio  Stock
Producto
Manzanas     100     30
Naranjas      80     50
Uvas         120     60
Peras         90     40

In [8]:
df.drop('Stock', axis=1, inplace=True)

In [9]:
df

          Precio
Producto
Manzanas     100
Naranjas      80
Platanos      60
Uvas         120
Peras         90