In [1]:
import pandas as pd

In [2]:
data = {
    'Producto':['Manzanas', 'Naranjas', 'Platanos', 'Uvas', 'Peras'],
    'Precio': [100, 80, 60, 120, 90],
    'Stock':[30,50,20,60,40]
}

df = pd.DataFrame(data)
df

   Producto  Precio  Stock
0  Manzanas     100     30
1  Naranjas      80     50
2  Platanos      60     20
3      Uvas     120     60
4     Peras      90     40

## Indexados

In [4]:
precios = df['Precio']
print(precios)

0    100
1     80
2     60
3    120
4     90
Name: Precio, dtype: int64

#### Seleccion por Etiquetas o nombres de filas Loc

In [6]:
producto_naranjas = df.loc[1,'Producto']
print(producto_naranjas)

Naranjas

In [8]:
producto_naranjas = df.loc[1]
print(producto_naranjas)

Producto    Naranjas
Precio            80
Stock             50
Name: 1, dtype: object

#### Seleccion por posicion Iloc

In [9]:
producto_posicion = df.iloc[2,1]
print(producto_posicion)

60

In [10]:
producto_posicion = df.iloc[2,0]
print(producto_posicion)

Platanos

In [11]:
df_nuevo = df.set_index("Producto")
df_nuevo

          Precio  Stock
Producto
Manzanas     100     30
Naranjas      80     50
Platanos      60     20
Uvas         120     60
Peras         90     40

In [13]:
df_nuevo.loc["Peras"]

Precio    90
Stock     40
Name: Peras, dtype: int64

## Selecciones

In [15]:
df_nuevo.iloc[3]

Precio    120
Stock      60
Name: Uvas, dtype: int64

## Filtrados

In [17]:
df_precios_altos = df[df['Precio']>80]
df_precios_altos

   Producto  Precio  Stock
0  Manzanas     100     30
3      Uvas     120     60
4     Peras      90     40

In [18]:
df_filtrado =df[(df['Precio'] > 60) & (df['Stock']>30)]

In [19]:
df_filtrado

   Producto  Precio  Stock
1  Naranjas      80     50
3      Uvas     120     60
4     Peras      90     40

In [20]:
df_where = df['Precio'].where(df['Precio']>80, other=0)
df_where

0    100
1      0
2      0
3    120
4     90
Name: Precio, dtype: int64

In [21]:
df_query = df.query('Precio > 80')
df_query

   Producto  Precio  Stock
0  Manzanas     100     30
3      Uvas     120     60
4     Peras      90     40