In [1]:
import pandas as pd

In [2]:
data = {
    'Producto':['Manzanas', 'Naranjas', 'Platanos', 'Uvas', 'Peras'],
    'Precio': [100, 80, 60, 120, 90]
}

df = pd.DataFrame(data)
df

   Producto  Precio
0  Manzanas     100
1  Naranjas      80
2  Platanos      60
3      Uvas     120
4     Peras      90

In [3]:
def descuento(x):
    return x * 0.85

In [4]:
df ['Precio_Descuento'] = df ['Precio'].apply(descuento)
df

   Producto  Precio  Precio_Descuento
0  Manzanas     100              85.0
1  Naranjas      80              68.0
2  Platanos      60              51.0
3      Uvas     120             102.0
4     Peras      90              76.5

In [7]:
df['Producto'] = df['Producto'].apply(lambda x: x.upper())
df

   Producto  Precio  Precio_Descuento
0  MANZANAS     100              85.0
1  NARANJAS      80              68.0
2  PLATANOS      60              51.0
3      UVAS     120             102.0
4     PERAS      90              76.5

In [10]:
df

   Producto  Precio
0  Manzanas     100
1  Naranjas      80
2  Platanos      60
3      Uvas     120
4     Peras      90

In [11]:
df['Producto'] = df['Producto'].map({'Manzanas': 'Apples', 'Naranjas': 'Oranges'})
df

  Producto  Precio
0   Apples     100
1  Oranges      80
2      NaN      60
3      NaN     120
4      NaN      90

In [3]:
df = df.map(lambda x: x.lower() if type(x) == str else x)

In [4]:
df

   Producto  Precio
0  manzanas     100
1  naranjas      80
2  platanos      60
3      uvas     120
4     peras      90

In [5]:
df['Descuento'] = [10, 15, 10, 20, 5]
df

   Producto  Precio  Descuento
0  manzanas     100         10
1  naranjas      80         15
2  platanos      60         10
3      uvas     120         20
4     peras      90          5

In [7]:
df['Precio_final'] = df.apply(lambda row:row['Precio'] * (100 - row ['Descuento']) / 100, axis=1)
df

   Producto  Precio  Descuento  Precio_final
0  manzanas     100         10          90.0
1  naranjas      80         15          68.0
2  platanos      60         10          54.0
3      uvas     120         20          96.0
4     peras      90          5          85.5

In [10]:
data = {
    'Producto':['Manzanas', 'Naranjas', 'Platanos', 'Uvas', 'Peras'],
    'Precio': [100, 80, 60, 120, 90]
}

df = pd.DataFrame(data)
df

   Producto  Precio
0  Manzanas     100
1  Naranjas      80
2  Platanos      60
3      Uvas     120
4     Peras      90

In [11]:
mapeo = {'Manzanas': 'Apples', 'Naranjas': 'Oranges'}
df['Producto'] = df['Producto'].map(lambda x: mapeo.get(x,x))
df

   Producto  Precio
0    Apples     100
1   Oranges      80
2  Platanos      60
3      Uvas     120
4     Peras      90