In [1]:
import pandas as pd

In [21]:
data ={'A': [1, 2, None, 4, 5],
       'B':[None,4,3,2,None,],
       'C':[2,3,4,None,6]}
df = pd.DataFrame(data)
df

     A    B    C
0  1.0  NaN  2.0
1  2.0  4.0  3.0
2  NaN  3.0  4.0
3  4.0  2.0  NaN
4  5.0  NaN  6.0

In [6]:
faltantes_por_columna = df.isnull().sum()
print("Número de valores faltantes por columna:\n", faltantes_por_columna)

Número de valores faltantes por columna:
 A    1
B    2
C    2
dtype: int64

In [9]:
df_sin_filas_faltantes = df.dropna()
print("DartaFrame sin filas con valores faltantes:\n", df_sin_filas_faltantes)

DartaFrame sin filas con valores faltantes:
      A    B    C
1  2.0  4.0  3.0

In [11]:
df_sin_filas_faltantes = df.dropna(axis = 1)
print("DartaFrame sin filas con valores faltantes:\n", df_sin_filas_faltantes)

DartaFrame sin filas con valores faltantes:
 Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [19]:
df_datos_relenados = df.fillna(0)
print("DartaFrame con valores faltantes rellenados con 0:\n", df_datos_relenados)

DartaFrame con valores faltantes rellenados con 0:
      A    B    C
0  1.0  0.0  2.0
1  2.0  4.0  3.0
2  0.0  3.0  4.0
3  4.0  2.0  0.0
4  5.0  0.0  6.0

In [23]:
df_datos_relenados = df.fillna(df.mean())
print("DartaFrame con valores faltantes rellenados con la media:\n", df_datos_relenados)

DartaFrame con valores faltantes rellenados con la media:
      A    B     C
0  1.0  3.0  2.00
1  2.0  4.0  3.00
2  3.0  3.0  4.00
3  4.0  2.0  3.75
4  5.0  3.0  6.00

In [24]:
df

     A    B    C
0  1.0  NaN  2.0
1  2.0  4.0  3.0
2  NaN  3.0  4.0
3  4.0  2.0  NaN
4  5.0  NaN  6.0

In [30]:
df_rellenado_ffill = df.ffill()
print("DartaFrame con valores faltantes rellenados con el valor anterior:\n", df_rellenado_ffill)

DartaFrame con valores faltantes rellenados con el valor anterior:
      A    B    C
0  1.0  NaN  2.0
1  2.0  4.0  3.0
2  2.0  3.0  4.0
3  4.0  2.0  4.0
4  5.0  2.0  6.0

In [32]:
df_rellenado_bfill = df.bfill()
print("DartaFrame con valores faltantes rellenados con el valor siguiente:\n", df_rellenado_bfill)

DartaFrame con valores faltantes rellenados con el valor siguiente:
      A    B    C
0  1.0  4.0  2.0
1  2.0  4.0  3.0
2  4.0  3.0  4.0
3  4.0  2.0  6.0
4  5.0  NaN  6.0